### ISSUE TITLE
Criar descrição do projeto

### ISSUE THREAD

**Issue by enieber** [meu-bairro/gerenciamento#1]
A ideia do projeto Meu Bairro é para ser uma rede comunitária para venda de produtos, prestação de serviços e divulgação.  Como uma rede comunitária, o projeto Meu Bairro poderá fornecer ferramentas para facilitar, organizar e compartilhar informações sobre produtos, serviços e eventos. Como intuito maior poderá aumentar a renda e ainda distribuir parte arrecadada com a venda de propagandas interna para criadores de conteúdo ou elaboração de eventos para o Meu Bairro.

**Comment by enieber** [comment]
A ideia é que o projeto se divida em algumas partes:

- servidor responsavel porgerenciar as informaçãoes
- app responsavle por mostrar as informações do bairro

**Comment by enieber** [comment]
A ideia do projeto é ser distribuido com a licensa AGPL 3.0

**Comment by enieber** [comment]
Para fechar a issue precisamos:

- [ ] Adicionar a descrição no readme do projeto
- [ ] Criar site com a descrição do projeto

**Comment by fatorius** [comment]
Agora que temos a logo e uma certa identidade visual para o projeto, poderiamos criar um repositório para o site com a descrição do projeto para que possamos contribuir com essa issue

**Comment by enieber** [comment]
@fatorius repositorio criado, agora só  criar o site e com base no layout sugerido na issue #2 link do repositorio:

https://github.com/meu-bairro/meu-bairro.github.io

**Comment by anliben** [comment]
@fatorius pode contar comigo para a construção do site também, ok?

**Comment by enieber** [comment]
![Screenshot 2024-04-12 at 22-47-09 Penpot Design Freedom for Teams](https://github.com/meu-bairro/gerenciamento/assets/7907068/fde51806-7817-455e-a281-2a08bf1f6e49)
![Screenshot 2024-04-12 at 22-47-31 Penpot Design Freedom for Teams](https://github.com/meu-bairro/gerenciamento/assets/7907068/83d72f45-8485-44ab-bd30-7288faa3b4dc)
![Screenshot 2024-04-12 at 22-47-43 Penpot Design Freedom for Teams](https://github.com/meu-bairro/gerenciamento/assets/7907068/19ca0dc0-71bd-4c82-a674-7328cb030524)
![Screenshot 2024-04-12 at 22-47-54 Penpot Design Freedom for Teams](https://github.com/meu-bairro/gerenciamento/assets/7907068/6054f050-8bcc-418a-8c00-4f4c4d433ff4)

**Comment by enieber** [comment]
![Screenshot 2024-04-12 at 22-55-48 Penpot Design Freedom for Teams](https://github.com/meu-bairro/gerenciamento/assets/7907068/1d3f5532-2c4e-48e9-bfba-cdcae343d6a9)

**Comment by enieber** [comment]
Acho que esse design para a primeira landpage está bem interessante.

**Comment by enieber** [comment]
Caso alguém queira implementar só falar comigo que eu passo o acesso ao Penpot do design

**Comment by enieber** [comment]
Temos o texto e o layout @joaooliveiradev , mas falta tempo e grana para fazer

**Comment by joaooliveiradev** [comment]
@enieber As vezes eu tenho algumas horinhas livres, posso ajudar, em o que estamos pensando em termos de tecnologia para fazer esse Layout?

 Reason/ReScript 👀

**Comment by enieber** [comment]
@joaooliveiradev podemos usar sim.. o unico requisito é que tenha nextjs para facilitar integrações no futuro...

Qualquer outra decisao de front pode ficar a cargo de quem for fazer.. pode ficar avontade

**Comment by enieber** [comment]
Criei um convite para o meu doscord, para conversarmos coisas mais especificas do projeto.

https://discord.com/invite/4XMzujjU

**Comment by enieber** [comment]
Vou fechar essa issue por conta do readme do projeto estar finalizada e abrir uma issue para o site

https://github.com/meu-bairro/.github/blob/main/profile/README.md
