### ISSUE TITLE
Criar Arquitetura do servidor

### ISSUE THREAD

**Issue by enieber** [meu-bairro/gerenciamento#3]
O servidor responsavel pelo meu bairro precisa ter algumas funcionalidades. De preferencia usar um protocolo de federação, para facilitar o consumo de informaçãoes independente do bairro.

Como sugestão podemos usar o protocolo [activitypub](https://activitypub.rocks/) que já é usado em algumas redes sociais o que pode facilitar a integração em redes federadas.

**Comment by enieber** [comment]
Uma possibilidade para agilizar o desenvolvimento e ao mesmo tempo termos uma performace muito boa é usar o loco.rs para criar toda a parte da api, como ele é focado em backend feito em rust e ainda não foi definido um padrão para frontend. O que nos da margem boa para decidir isso separadamente. Outra coisa interessante é que sendo um spa o proprio loco consegue renderizar isso.

**Comment by enieber** [comment]
Acho interessante desenvolvermos primeiro o modelo de dados e seu relacionamento entre as tabelas e depois criarmos a api usando o loco.rs e depois desenharmos as telas. Podemos criar uma issue para cada feature e fazer em paralelo coisas como protipo de tela e a parte do banco entre outras partes.

**Comment by anliben** [comment]
Eu concordo plenamente no entanto necessito ver uma URL funcionando com o loco.rs entao irei subir um repositorio teste dele para podermos entender como ficar nos ambiente de dev e prod. com banco de dados, redis, smtp

**Comment by enieber** [comment]
Boa.. se quiser subir um projeto com api:

https://github.com/enieber/hagrid_api

**Comment by enieber** [comment]
Com base no protocolo activity pub podemos usar [o conseito de actors](https://www.w3.org/TR/activitypub/#actors) para criar o "Work" responsavel pelo inbox das empresas
