### ISSUE TITLE
Criar Logo para Meu bairro

### ISSUE THREAD

**Issue by enieber** [meu-bairro/gerenciamento#4]
Para criar a logo precisa de algumas informações como:

- paleta de cores
- que informação quer passar com a logo
- quais fontes usar na tipografia da logo (texto usado junto a logo)

Com essas informações o que se espera é:

- uma imagem em png para uso nas plataformas como github
- uma imagem de fundo
- exemplos de uso da logo

**Comment by enieber** [comment]
Com a ideia Comunidade + Bairro + rede fiz esse esboço.

![Board(2)](https://github.com/meu-bairro/gerenciamento/assets/7907068/e37f576b-df0a-4550-9197-a6fa47162aba)

Queria que tivesse algo relacionado a raises como rede de conexão entre as casas do meu bairro, mas me falta conhecimentos tecnicos para coloar essa ideia em pratica.

**Comment by anliben** [comment]
![meu bairro](https://github.com/meu-bairro/gerenciamento/assets/45929971/bc4b9bb6-22a2-48c6-bc36-1fce0aaf406f)

Acreditamos que, em nossa sociedade, está faltando a colaboração, a comunicação e a transparência! Para isso empegamos em nosso logo uma piramide inacabada

obs; Texto meramente ilustrativo para passar a ideia do logo

**Comment by enieber** [comment]
Gostei disso: comunicação e a transparência no seu bairro

**Comment by enieber** [comment]
Para a primeira versão vamos usar essa logo:


![Image](https://github.com/meu-bairro/gerenciamento/assets/7907068/86516c0b-17d7-41db-9531-e1796b837e7a)

**Comment by enieber** [comment]
Caso haja alguma alteração na logo será colocando nesse repositorio:
 https://github.com/meu-bairro/logo
