### ISSUE TITLE
Escolha da Stack

### ISSUE THREAD

**Issue by enieber** [meu-bairro/gerenciamento#6]
Para separar a discução e aprofundar os motivos que nos levam a escolher as tecnologias que escolhemos, vou abrir essa issue.

## Backend 

Para escolha do backend tem que se levar em consideração algumas coisas como:

- facilidade de instalação, de preferencia um binario unico.
- bom uso dos recurso, como o menor uso de cpu e memoria possivel (quem sabe rodar em uma geladeira)
- menor custo de manutenção
- afinidade com a linguagem

Por esses motivos minha preferencia é por usar rust.

## Frontend

TODO: @joaooliveiradev

**Comment by joaooliveiradev** [comment]
<h1>Front End</h1>

Framework: NextJS -> Amplamente usado pela comunidade Front End e supre todas as necessidades do projeto
Linguagem: ReScript -> Compila para JavaScript assim como Typescript porém tem compilador mais rapido, um sistema de tipos mais forte e também tem algumas features a mais como pipe operator e pattern matching.

O que acha @enieber ?
